version: '3.9'
services:
  sales_django:
    build:
      context: ./step1_sales_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./step1_sales_django/:/usr/src/app/
    ports:
      - "8000:8000"
  orders_flask:
    build:
      context: ./step2_orders_flask
    depends_on:
      - rabbitmq
    restart: on-failure
    environment:
      - FLASK_APP=main.py
      - FLASK_RUN_HOST=0.0.0.0
    command: flask run
    volumes:
      - ./step2_orders_flask/:/usr/src/app/
    ports:
      - "5000:5000"
  repair_rabbit:
    build:
      context: ./step3_repair_rabbit
    depends_on:
      - rabbitmq
    restart: on-failure
    command: python main.py
    volumes:
      - ./step3_repair_rabbit/:/usr/src/app/
  rabbitmq:
    image: rabbitmq:3.9-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq/data
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:15672" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  rabbitmq: